### ISSUE TITLE
Error: Cannot find module 'react-storefront-magento2-connector'

### ISSUE THREAD

**Issue by asgne** [react-storefront-community/react-storefront#104]
# Bug report

## Describe the bug

After creating an app with:

`npm create react-storefront --yes (my-app-name)`

And trying to run dev I get the error:

`UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-storefront-magento2-connector'`

Although I've not configured anything yet.

## To Reproduce

1. Clone react-storefront repo
2. Create an instance of react-storefront
3. CD into app and attempt to run `npm run dev`
4. Error in console appears after trying to compile

## Expected behavior

The newly created storefront should start as intended.

## Screenshots

<img width="1146" alt="Screen Shot 2020-06-12 at 11 42 16 AM" src="https://user-images.githubusercontent.com/65558711/84527631-dae04900-aca3-11ea-9f52-6201c02540ef.png">

## System information

- OS: macOS
- Version of React Storefront: 8.9.0

Thanks!

**Comment by markbrocato** [comment]
This was due to an error in the next.config.js file in react-storefront-starter-app and is now fixed.

**Comment by markbrocato** [comment]
Here is the relevant line that needs to be updated:
https://github.com/react-storefront-community/react-storefront-starter-app/blob/master/next.config.js#L7

**Comment by asgne** [comment]
Thank you!
