### ISSUE TITLE
Questions regarding storefront versions & deployment

### ISSUE THREAD

**Issue by nilesh-parab** [react-storefront-community/react-storefront#116]
I was searching for a storefront & found couple of boilerplate for **react-storefront**. 
I am little confused as to what each offers & how they are different. So far the with the documentation I went through, I believe both are same. Here are the links I found:
- [react-storefront from react-storefront-community](https://github.com/react-storefront-community/react-storefront)
- [react-storefront from moovweb](https://github.com/moovweb/react-storefront)

The other help I needed was on how to deploy it **other than Moovweb XDN**? Like if we want to deploy it to say Heroku or Netlify or even EC2?
The only detail I could find related to this was [this stackoverflow issue](https://stackoverflow.com/questions/54626007/how-to-start-react-storefront-moovweb-on-express-server) which points that express needs to be added. Not sure, how does routing affects the hosting platform?

Any information / help could really help me understand this storefront better. Thank you.

**Comment by markbrocato** [comment]
Use this repo. The older react-storefront under the moovweb org is in maintenance mode and will not continue to receive new features. It is on version 6 while this repo is already on version 8.

React Storefront v7 and beyond is based on Next.js, so building and deploying it is the same as any other Next.js app. Use the following command to create a new React Storefront app:

```
npm create react-storefront@latest my-app
```

It will ask you if you want to deploy on the Moovweb XDN.  Just answer no and it will create an app with the usual Next.js setup.

**Comment by nilesh-parab** [comment]
Thank you for quick reply @markbrocato , this clears up everything.
