### ISSUE TITLE
Custom Hamburger Menu Icon

### ISSUE THREAD

**Issue by marina-marina** [react-storefront-community/react-storefront#80]
1) Hamburger `MenuButton` icon is hardcoded and the user can't pass a custom icon there:
https://github.com/react-storefront-community/react-storefront/blob/master/src/menu/MenuButton.js#L42

2) MenuIcon can't be customised in a way so that AMP guidelines are supported.
Inside `MenuIcon` component it is needed to apply `!important` to customise the menu icon which does not meet the guidelines of AMP:
https://github.com/react-storefront-community/react-storefront/blob/master/src/menu/MenuIcon.js#L132

## Expected behaviour

The users of RSF should be able to add custom hamburger menu icon or customise it passing down classes without writing `.class > div > span: { style: !important }`

## Screenshots
![image](https://user-images.githubusercontent.com/2051028/81672574-0082f400-9453-11ea-954a-5af655565100.png)

**Comment by kevhender** [comment]
@marina-marina This is already possible by using the `MenuIcon` property of the `MenuButton` (see [docs](https://docs.reactstorefront.io/apiReference/menu/MenuButton#prop-MenuIcon)).

Here I have changed this to use a different icon:
```js
import { Apps } from '@material-ui/icons'
...

export default function Header({ menu }) {
  ...

  return (
    ...
      <MenuButton open={menuOpen} onClick={handleMenuButtonClick} MenuIcon={Apps} />
    ...
  )
}
```
![Screen Shot 2020-05-12 at 10 21 50 AM](https://user-images.githubusercontent.com/2205550/81703459-a118ea00-943a-11ea-8831-81feb65b95e3.png)
