### ISSUE TITLE
Can't run the project in local development???

### ISSUE THREAD

**Issue by rajmaxi** [react-storefront-community/react-storefront#87]
I was followed by the instruction given in the GitHub for local development. Moreover, I haven't able to run this in my local machine. When I was run the command of npm run watch and I got the error as 
[nodemon] app crashed like this. I have attached the screenshot and could you please help me on this to solve this issue
![Capture2](https://user-images.githubusercontent.com/41547672/82619650-1f704b80-9bf4-11ea-9606-6f6b7c880abb.png)

**Comment by markbrocato** [comment]
It looks like the scripts for watching and compiling react storefront aren't compatible with windows.  Are you trying to make changes to the react-storefront library itself, or create an app based on react-storefront?

**Comment by rajmaxi** [comment]
Thanks for the valuable response.  I have tried to run the project using react-storefront only but whenever I have run this project using npm start, I got the error. I have attached the screenshot for the reference. My only concern was how to run this GitHub project in the local server.
![Capture6](https://user-images.githubusercontent.com/41547672/82645660-dd192f80-9c30-11ea-8859-2df65eaad3c0.png)

**Comment by markbrocato** [comment]
This repo contains the React Storefront framework, not an app.  So there is no start script.  You can run `npm watch` or `npm build` to transpile the source so it can be used in an app.  I suspect what you actually want is to create an app.  For that you should use `npm create react-storefront@latest`.
